#!/usr/bin/env python3
"""Source-level gates for the GenLayer milestone settlement release.

These checks make the milestone feature independently reviewable without
changing the existing deployed-case gates. Runtime checks remain authoritative
and are run by ``scripts/milestone_verify.sh``.
"""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTROLLER_PATH = ROOT / "contracts/verdict_graph_milestone.py"
AUTHORITY_PATH = ROOT / "contracts/verdict_graph_milestone_authority.py"
REGISTRY_PATH = ROOT / "contracts/verdict_graph_milestone_registry.py"
ADJUDICATOR_PATH = ROOT / "contracts/verdict_graph_milestone_adjudicator.py"
VAULT_PATH = ROOT / "evm/contracts/VerdictGraphMilestoneVault.sol"
FRONTEND_CLIENT_PATH = ROOT / "frontend/lib/genlayer/client.ts"
FRONTEND_VAULT_PATH = ROOT / "frontend/lib/genlayer/milestone-vault.ts"
FRONTEND_CONFIG_PATH = ROOT / "frontend/components/milestone-configuration-required.tsx"
FRONTEND_ACTIONS_PATH = ROOT / "frontend/components/milestone-actions.tsx"
FRONTEND_VALIDATION_PATH = ROOT / "frontend/lib/milestone-validation.ts"
FRONTEND_AUTHORITY_PATH = ROOT / "frontend/app/milestones/authority/page.tsx"
FRONTEND_CREATE_PATH = ROOT / "frontend/app/milestones/create/page.tsx"
FRONTEND_LIST_PATH = ROOT / "frontend/app/milestones/page.tsx"
FRONTEND_PROOF_PATH = ROOT / "frontend/lib/milestone-proof.ts"
FRONTEND_NEXT_CONFIG_PATH = ROOT / "frontend/next.config.mjs"
FRONTEND_ERROR_PATH = ROOT / "frontend/app/error.tsx"
FRONTEND_LOADING_PATH = ROOT / "frontend/app/loading.tsx"
FRONTEND_NOT_FOUND_PATH = ROOT / "frontend/app/not-found.tsx"
MILESTONE_TEMPLATE_PATH = ROOT / "deploy/milestone-bradbury.template.json"
MILESTONE_ARTIFACT_BUILD_PATH = ROOT / "scripts/build_milestone_deploy_artifact.py"
MILESTONE_DEPLOY_CONTROLLER_PATH = ROOT / "contracts/verdict_graph_milestone_deploy.py"
MILESTONE_DEPLOY_AUTHORITY_PATH = ROOT / "contracts/verdict_graph_milestone_authority_deploy.py"
MILESTONE_DEPLOY_REGISTRY_PATH = ROOT / "contracts/verdict_graph_milestone_registry_deploy.py"
MILESTONE_DEPLOY_ADJUDICATOR_PATH = ROOT / "contracts/verdict_graph_milestone_adjudicator_deploy.py"
MILESTONE_CONTROLLER_PROBE_PATH = ROOT / "scripts/milestone_bradbury_deploy_estimate.mjs"
MILESTONE_VAULT_PROBE_PATH = ROOT / "scripts/milestone_vault_deploy_estimate.mjs"
MILESTONE_VAULT_HASH_PATH = ROOT / "scripts/milestone_vault_runtime_hash.py"
MILESTONE_VERIFY_PATH = ROOT / "scripts/milestone_verify.sh"
MILESTONE_PREFLIGHT_PATH = ROOT / "scripts/milestone_bradbury_preflight.sh"
DIRECT_TEST_PATH = ROOT / "tests/direct/test_milestone_controller.py"
AUTHORITY_TEST_PATH = ROOT / "tests/direct/test_milestone_authority.py"
REGISTRY_TEST_PATH = ROOT / "tests/direct/test_milestone_registry.py"
ADJUDICATOR_TEST_PATH = ROOT / "tests/direct/test_milestone_adjudicator.py"
EVM_TEST_PATH = ROOT / "evm/test/VerdictGraphMilestoneVault.t.sol"


def read(path: Path) -> str:
    if not path.is_file():
        raise SystemExit(f"FAIL missing required release file: {path.relative_to(ROOT)}")
    return path.read_text()


controller = read(CONTROLLER_PATH)
authority = read(AUTHORITY_PATH)
registry = read(REGISTRY_PATH)
adjudicator = read(ADJUDICATOR_PATH)
vault = read(VAULT_PATH)
frontend_client = read(FRONTEND_CLIENT_PATH)
frontend_vault = read(FRONTEND_VAULT_PATH)
frontend_config = read(FRONTEND_CONFIG_PATH)
frontend_actions = read(FRONTEND_ACTIONS_PATH)
frontend_validation = read(FRONTEND_VALIDATION_PATH)
frontend_authority = read(FRONTEND_AUTHORITY_PATH)
frontend_create = read(FRONTEND_CREATE_PATH)
frontend_list = read(FRONTEND_LIST_PATH)
frontend_proof = read(FRONTEND_PROOF_PATH)
frontend_next_config = read(FRONTEND_NEXT_CONFIG_PATH)
frontend_error = read(FRONTEND_ERROR_PATH)
frontend_loading = read(FRONTEND_LOADING_PATH)
frontend_not_found = read(FRONTEND_NOT_FOUND_PATH)
template = read(MILESTONE_TEMPLATE_PATH)
direct_tests = read(DIRECT_TEST_PATH)
evm_tests = read(EVM_TEST_PATH)
milestone_controller_probe = read(MILESTONE_CONTROLLER_PROBE_PATH)
milestone_vault_probe = read(MILESTONE_VAULT_PROBE_PATH)
milestone_vault_hash = read(MILESTONE_VAULT_HASH_PATH)
milestone_verify = read(MILESTONE_VERIFY_PATH)
milestone_preflight = read(MILESTONE_PREFLIGHT_PATH)
milestone_artifact_build = read(MILESTONE_ARTIFACT_BUILD_PATH)
milestone_deploy_controller = read(MILESTONE_DEPLOY_CONTROLLER_PATH)
milestone_deploy_authority = read(MILESTONE_DEPLOY_AUTHORITY_PATH)
milestone_deploy_registry = read(MILESTONE_DEPLOY_REGISTRY_PATH)
milestone_deploy_adjudicator = read(MILESTONE_DEPLOY_ADJUDICATOR_PATH)
authority_tests = read(AUTHORITY_TEST_PATH)
registry_tests = read(REGISTRY_TEST_PATH)
adjudicator_tests = read(ADJUDICATOR_TEST_PATH)

checks = {
    "controller is a GenLayer IC": "class VerdictGraphMilestone(gl.Contract):" in controller,
    "Bradbury artifacts are generated by a parity-checked build": all(token in milestone_artifact_build for token in ("reversible AST proof", "preserve the public and storage surfaces", "StripDocstrings", "RenameInternalSymbols", "deploy_path.write_bytes", "PAIRS")) and "build_milestone_deploy_artifact.py" in milestone_verify,
    "milestone trust root, lifecycle and subjective review are split into three ICs": all(token in authority for token in ("class VerdictGraphMilestoneAuthority(gl.Contract):", "accepted_projects", "Only the acceptance authority can register a project", "get_project_snapshot")) and all(token in registry for token in ("class VerdictGraphMilestoneRegistry(gl.Contract):", "authority_address: Address", "bind_adjudicator", "record_review", "VerdictGraphMilestoneAuthority")) and all(token in adjudicator for token in ("class VerdictGraphMilestoneAdjudicator(gl.Contract):", "gl.vm.run_nondet_unsafe", "VerdictGraphMilestoneRegistry", "request_results")) and "accepted_projects" not in registry,
    "each split deployment artifact is dependency-pinned and materially smaller": all(len(deploy.encode()) < len(source.encode()) and deploy.startswith('# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }') for source, deploy in ((authority, milestone_deploy_authority), (registry, milestone_deploy_registry), (adjudicator, milestone_deploy_adjudicator))),
    "Bradbury artifact is materially smaller and dependency-pinned": len(milestone_deploy_controller.encode()) < len(controller.encode()) and milestone_deploy_controller.startswith('# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }'),
    "controller pins the GenVM dependency": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" in controller,
    "split source identities are constructor-bound": all(token in authority for token in ("authority_source_sha256: str", "Authority source SHA-256", "get_authority_source_sha256")) and all(token in registry for token in ("registry_source_sha256: str", "get_registry_source_sha256", "_hash(registry_source_sha256)")) and all(token in adjudicator for token in ("adjudicator_source_sha256: str", "Adjudicator source SHA-256", "get_adjudicator_source_sha256")) and (all(token in template for token in ("<authorityDeploymentArtifactSha256>", "<registryDeploymentArtifactSha256>", "<adjudicatorDeploymentArtifactSha256>")) or all(token in template for token in ("12f96a55796d2277a58cb081ed72818c99ff85adde28fc0d8bf7789fd5077bc8", "03e2248d139b2870a0d989ddeb42d684df029eabf07f923233ba569668e172bf", "db1e3467f3983989bc4212d08f2419db701ad6229f85d32527f66c8b6e4e4858"))),
    "leader and validator use custom nondeterministic consensus": "gl.vm.run_nondet_unsafe" in controller and "def validator_fn(" in controller,
    "validators independently fetch baseline and submission": "gl.nondet.web.request" in controller and "validator_data = self._review_milestone" in controller,
    "model output is exact and bounded": 'DECISIONS = ("PASS", "FAIL", "UNDETERMINED")' in controller and "_normalize_model_result" in controller,
    "accepted project provenance is sponsor-bound and authority-gated": all(token in controller for token in ("acceptance_authority: Address", "sponsor: Address", "register_accepted_project", "Only the acceptance authority can register a project", "Only the registered project sponsor can create milestones", "Milestone must reference an authority-registered accepted project")),
    "evidence origins are public, authority-registered and mirror-backed": all(token in controller for token in ("_uri_origin", "submission_origins_json", "baseline_mirror_uri", "acceptance_record_mirror_uri", "ALL_SOURCES_FAILED", "Submission URI origin is not an authority-registered evidence origin")),
    "milestone deadlines have bounded safety windows": all(token in controller for token in ("MIN_FUNDING_WINDOW_SECONDS = 900", "MIN_SUBMISSION_WINDOW_SECONDS = 900", "MIN_RECOVERY_BUFFER_SECONDS = 900", "MIN_CHALLENGE_WINDOW_SECONDS = 300", "MAX_CHALLENGE_WINDOW_SECONDS = 30 * 24 * 60 * 60", "MAX_MILESTONE_HORIZON_SECONDS = 365 * 24 * 60 * 60")),
    "milestone references are unique and lookup-safe": "milestone_by_reference" in controller and "get_milestone_for_reference" in controller and "Milestone reference is already used" in controller,
    "consequences are exact pre-registered rules": all(token in controller for token in ("CONSEQUENCE_PASS = 1", "CONSEQUENCE_FAIL = 2", "CONSEQUENCE_NEUTRAL = 3")),
    "terms and evidence are hash pinned": all(token in controller for token in ("terms_sha256", "baseline_sha256", "submission_sha256", "source_set_sha256", "review_sha256")),
    "repair state is persisted": "repair_failure_code" in controller and "repair_observed_sha256" in controller,
    "review input and rendered prompt have bounded byte budgets": all(token in controller for token in ("MAX_REVIEW_INPUT_BYTES = 32_000", "MAX_REVIEW_PROMPT_BYTES = 64_000", "REVIEW_INPUT_TOO_LARGE", "REVIEW_PROMPT_TOO_LARGE")),
    "challenge attribution and history are persisted": all(token in controller for token in ("challenged_by: Address", "challenged_at: u256", "challenge_history", "milestone.challenged_by = gl.message.sender_address", "get_challenge")),
    "review digest excludes unverified prose": '"source_set_sha256": consensus_result["source_set_sha256"],\n        }' in controller and '"summary": consensus_result["summary"]' not in controller.split("review_payload =", 1)[1].split("review_sha256", 1)[0],
    "review prompt structurally isolates untrusted text": all(token in controller for token in ("VERDICTGRAPH_MILESTONE_REVIEW_V2", "_base64_utf8", "BASELINE_BASE64", "SUBMISSION_BASE64", "CHALLENGE_BASE64")) and "<UNTRUSTED_CONTENT>" not in controller,
    "split adjudicator reviews the accepted record as evidence": all(token in adjudicator for token in ("acceptance = self._fetch_document", "ACCEPTANCE_RECORD_BASE64", "acceptance[\"text\"]")),
    "split registry gates downstream lifecycle actions": all(token in registry for token in ("E42", "E25", "self._require_participant(milestone)")),
    "challenge window is bounded": "MAX_CHALLENGES = 2" in controller and "challenge_count" in controller and "challenge_deadline" in controller,
    "settlement is finality-only and retryable": ".emit().register_milestone" in controller and ".emit().apply_final_outcome" in controller and "settlement_attempt_count" in controller,
    "controller does not synchronously read EVM state": "VerdictGraphMilestoneVault(self.vault_address).view()" not in controller and "EthCall" not in controller,
    "vault Registry controller is immutable": "address public immutable milestone_registry;" in vault and "modifier onlyMilestoneRegistry()" in vault and "function milestone_core() external view returns (address)" in vault,
    "vault accepts only exact registered terms": "keccak256(bytes(milestone.termsSha256)) != keccak256(bytes(termsSha256))" in vault,
    "vault ignores duplicate finality safely": "mapping(uint256 => bool) public processedMilestones;" in vault and "MILESTONE_ALREADY_PROCESSED" in vault,
    "vault has exact pass fail neutral payout rules": all(token in vault for token in ("CONSEQUENCE_PASS = 1", "CONSEQUENCE_FAIL = 2", "CONSEQUENCE_NEUTRAL = 3", "principal + bond", "claimable[milestone.owner] += principal")),
    "vault has deadline recovery": "function recover_unactivated" in vault and "function recover_active" in vault and "RECOVERY_DEADLINE_EXPIRED" in vault,
    "vault rejects late finalized outcomes": "OUTCOME_AFTER_RECOVERY_DEADLINE" in vault and "block.timestamp > milestone.recoveryDeadline" in vault and "testOutcomeAfterRecoveryDeadlineCannotSettle" in evm_tests,
    "controller recovery uses deterministic Vault recovery": "def recover_milestone" in controller and ".emit().recover_active" in controller,
    "deployment preflight estimates every split artifact without sending": "eth_estimateGas" in milestone_controller_probe and "eth_estimateGas" in milestone_vault_probe and "eth_send" not in milestone_vault_probe and "no private key" in milestone_controller_probe.lower() and all(token in milestone_preflight for token in ("verdict_graph_milestone_authority_deploy.py", "verdict_graph_milestone_registry_deploy.py", "verdict_graph_milestone_adjudicator_deploy.py", "VERDICTGRAPH_MILESTONE_CONSTRUCTOR_ARGS_JSON")),
    "Vault runtime hash is enforced after build": all(token in milestone_verify for token in ("EXPECTED_RUNTIME", "ACTUAL_RUNTIME", "milestone Vault runtime hash drift", "expectedVaultRuntimeSha256", "milestone_vault_runtime_hash.py")) and all(token in milestone_vault_hash for token in ("immutable", "sha256", "unexpected immutable placeholder count")),
    "vault uses pull withdrawal and reentrancy lock": "mapping(address => uint256) public claimable" in vault and "function withdraw()" in vault and "modifier nonReentrant()" in vault,
    "milestone Vault security regression suite": all(token in evm_tests for token in ("testWithdrawReentrancyCannotDoubleSpend", "testWithdrawalFailureRestoresClaimableBalance", "testPayoutOverflowIsRejectedAtRegistration", "testFuzzPassPayoutIsExact")),
    "vault rejects unsolicited native transfers": "fallback() external payable" in vault and "revert InvalidTerms()" in vault,
    "frontend reads finalized controller state": "getMilestoneAddress" in frontend_client and "TransactionHashVariant.LATEST_FINAL" in frontend_client,
    "frontend verifies reciprocal controller-vault topology": "get_vault_address" in frontend_vault and "milestone_core" in frontend_vault and "does not match configured deployment" in frontend_vault,
    "frontend fails closed before milestone writes": "isMilestoneConfigured()" in frontend_vault and "verifyMilestoneTopology()" in frontend_vault,
    "frontend verifies deployed Authority, Registry, Adjudicator and Vault identity": all(token in frontend_vault for token in ("getBytecode", "getMilestoneVaultRuntimeSha256", "getMilestoneAuthoritySourceSha256", "getMilestoneRegistrySourceSha256", "getMilestoneAdjudicatorSourceSha256", "get_authority_source_sha256", "get_registry_source_sha256", "get_adjudicator_source_sha256", "source digest does not match", "runtime bytecode does not match")) and all(token in frontend_client for token in ("NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_AUTHORITY_ADDRESS", "NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_REGISTRY_ADDRESS", "NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_ADJUDICATOR_ADDRESS", "NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_AUTHORITY_SOURCE_SHA256", "NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_REGISTRY_SOURCE_SHA256", "NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_ADJUDICATOR_SOURCE_SHA256")),
    "frontend rechecks chain and reverted receipts": "assertBradburyNetwork" in frontend_client and 'receipt.status !== "success"' in frontend_vault,
    "frontend waits for downstream settlement state": "waitForMilestoneVaultStatus" in frontend_vault and "expectedVaultStatus" in frontend_actions,
    "frontend exposes challenge, recovery and withdrawal controls": "challenge_milestone" in frontend_actions and "recover_unactivated" in frontend_actions and "recover_active" in frontend_actions and "Withdraw" in frontend_actions and "Queue exact settlement" in frontend_actions,
    "frontend exposes the acceptance authority workflow": "register_accepted_project" in frontend_authority and "get_acceptance_authority" in frontend_authority and "FileHashHelper" in frontend_authority,
    "frontend uses authority project refs and race-safe lookup": "Accepted project reference" in frontend_create and "get_milestone_for_reference" in frontend_create,
    "frontend bounds milestone list fanout with pagination": "MAX_MILESTONES_PER_LOAD = 50" in frontend_list and "Previous page" in frontend_list and "Next page" in frontend_list and "queryKey: [\"milestones\", page]" in frontend_list,
    "frontend validates public and authority-registered evidence origins": "isIpv4Literal" in frontend_validation and "allowedOriginsJson" in frontend_validation and "allowedSubmissionOriginsJson" in frontend_actions,
    "proof pack includes split provenance history and versioned deployment identity": all(token in frontend_proof for token in ("milestone-proof.v5", "protocol_state", "currentReview", "acceptance_authority_registered", "acceptance_record_sha256", "challenges", "vault_terms_match", "milestone_authority_source_sha256", "milestone_registry_source_sha256", "milestone_adjudicator_source_sha256", "block_hash")),
    "Vault proof reads are anchored to an EVM block": all(token in frontend_vault for token in ("getBlock", "blockNumber", "blockHash", "block.hash")),
    "publication has route recovery and security headers": all(token in frontend_next_config for token in ("Content-Security-Policy", "X-Content-Type-Options", "X-Frame-Options", "Strict-Transport-Security")) and all(token in frontend_error for token in ("reset", "Runtime recovery")) and "Loading finalized state" in frontend_loading and "That record does not exist" in frontend_not_found,
    "frontend exposes deployment-not-configured state": all(token in frontend_config for token in ("Milestone deployment is not configured", "NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_AUTHORITY_ADDRESS", "NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_REGISTRY_ADDRESS", "NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_ADJUDICATOR_ADDRESS", "NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_ADJUDICATOR_SOURCE_SHA256", "NEXT_PUBLIC_VERDICTGRAPH_MILESTONE_VAULT_RUNTIME_SHA256")),
    "deployment template has truthful pending/live state": '"schema": "verdictgraph-milestone-bradbury-deployment-v4-split"' in template and ((('"deploymentStatus": "NOT_DEPLOYED"' in template) and all(token in template for token in ('"authorityAddress": null', '"registryAddress": null', '"adjudicatorAddress": null', '"vaultAddress": null', '"acceptanceAuthorityAddress": null'))) or (('"deploymentStatus": "FINALITY_PENDING"' in template) and all(token in template for token in ('"authorityAddress": "0x', '"registryAddress": "0x', '"adjudicatorAddress": "0x', '"vaultAddress": "0x', '"acceptanceAuthorityAddress": "0x', '"authorityDeployTransaction": "0x', '"registryDeployTransaction": "0x', '"adjudicatorDeployTransaction": "0x', '"vaultDeployTransaction": "0x', '"bindAdjudicatorTransaction": null', '"bindVaultTransaction": null', '"verifiedAt": null'))) or (('"deploymentStatus": "DEPLOYED"' in template) and all(token in template for token in ('"authorityAddress": "0x', '"registryAddress": "0x', '"adjudicatorAddress": "0x', '"vaultAddress": "0x', '"acceptanceAuthorityAddress": "0x', '"authorityDeployTransaction": "0x', '"registryDeployTransaction": "0x', '"adjudicatorDeployTransaction": "0x', '"bindAdjudicatorTransaction": "0x', '"vaultDeployTransaction": "0x', '"bindVaultTransaction": "0x', '"verifiedAt": "')))),
    "Direct Mode covers milestone consensus and repair": all(token in direct_tests for token in ("test_submission_is_hash_pinned_and_consensus_binds_exact_outcome", "test_validator_rejects_different_milestone_outcome", "test_fetch_hash_failure_is_persisted_and_repair_can_submit_new_version", "test_authority_mirror_recovers_a_primary_baseline_outage", "test_review_input_budget_persists_repair_state")),
    "Direct Mode covers authority sponsor and race-safe references": "test_acceptance_authority_and_milestone_reference_are_enforced" in direct_tests and "Only the registered project sponsor can create milestones" in controller,
    "Direct Mode covers bounded challenge review": "test_bounded_challenge_reopens_review_and_binds_challenge_count" in direct_tests,
    "Foundry covers exact economic outcomes and recovery": all(token in evm_tests for token in ("testPassPaysBeneficiaryExactPrincipalAndBondOnce", "testBreachOutcomeReturnsExactPrincipalAndBondToOwner", "testNeutralOutcomeSplitsPrincipalAndBond", "testActiveRecoveryReturnsFundsAndBecomesTerminal", "testUnactivatedRegisteredRecoveryReturnsEmptyEscrow", "testUnactivatedFundedRecoveryReturnsPrincipal")),
    "Direct Mode covers every split milestone IC": all(token in authority_tests for token in ("test_authority_is_write_once_and_exports_a_canonical_snapshot", "test_authority_rejects_same_source_and_malformed_public_origins")) and all(token in registry_tests for token in ("test_registry_owns_lifecycle_and_authenticates_finalized_adjudicator_callbacks", "test_registry_rejects_unbound_authority_snapshots_and_keeps_binding_one_shot")) and all(token in adjudicator_tests for token in ("test_adjudicator_runs_validator_equivalence_and_caches_exact_request_result", "test_adjudicator_persists_repair_result_when_hash_pinned_document_is_unavailable")),
}

failed = [name for name, ok in checks.items() if not ok]
for name, ok in checks.items():
    print(f"{'PASS' if ok else 'FAIL'}  {name}")

if failed:
    raise SystemExit("\nMilestone source gates failed: " + ", ".join(failed))

print(f"\n{len(checks)}/{len(checks)} milestone source gates passed.")
